version: '3.5'

services:
  lumen:
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S lumen:80 -t public
    restart: always
